### ISSUE TITLE
the code base does not run

### ISSUE THREAD

**Issue by rlkant18** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#2]
I am trying to run your code, but it is not running on my local machine

**Comment by AmitXShukla** [comment]
can you please include any Angular console log and browser console log details, error or any other details?

**Comment by rlkant18** [comment]
<img width="1242" alt="Screen Shot 2019-07-05 at 10 22 22 PM" src="https://user-images.githubusercontent.com/16281804/60750220-71c06380-9f73-11e9-88b8-c183d9a402b8.png">
<img width="1680" alt="Screen Shot 2019-07-05 at 10 22 28 PM" src="https://user-images.githubusercontent.com/16281804/60750221-71c06380-9f73-11e9-97fe-86c8bf6d61f1.png">
so when I run the code, it compiles, but in the browser nothing shows up.

**Comment by AmitXShukla** [comment]
Browser-> Console log
What do you see there?

**Comment by rlkant18** [comment]
<img width="1677" alt="Screen Shot 2019-07-06 at 6 31 39 AM" src="https://user-images.githubusercontent.com/16281804/60755015-c259b000-9fb7-11e9-9532-7b4f97a88600.png">

**Comment by AmitXShukla** [comment]
did you setup for Firebase and changed to your own API_KEY?
