### ISSUE TITLE
Can not login as admin to mange product

### ISSUE THREAD

**Issue by Thomas-Ahn** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#4]
Got "Error: You are not authorized Admin" when signin admin , please let me know how I can manage products and upload image file..

**Comment by swaminathAK** [comment]
Did Anyone get solution for this issue? I am also getting same error while login as Admin.. followed all steps mentioned in video on youtube

**Comment by AmitXShukla** [comment]
You need a Firebase collection “estore”, inside this collection, you will need to create one document with document I’d = uid of the person who is admin, and inside this document, set a property isadmin=true

**Comment by AmitXShukla** [comment]
![image](https://user-images.githubusercontent.com/20031132/71873449-0d25c300-30d4-11ea-82b4-ff38c9fad88c.png)

**Comment by PhMari3** [comment]
I'm getting the same error, even if my Firebase is properly built and I've followed exactly all steps mentioned in video
Also thank you for all your work

**Comment by AmitXShukla** [comment]
> 
> 
> I'm getting the same error, even if my Firebase is properly built and I've followed exactly all steps mentioned in video
> Also thank you for all your work

can you please include a pic of your estore collection, you will see a document for your NUID, please include screenshot of this document here.

**Comment by PhMari3** [comment]
I don't have an estore collection. I have only what you have created in your video tutorial. This is how my Firebase looks like:
![1](https://user-images.githubusercontent.com/75609966/103208134-f1cd4c80-4910-11eb-92bc-24d9071d2ecb.png)

These are the rules of the Firebase.

```
  match /onlinestore/{document} {
	allow read: if false;
  	allow write: if false;
  }
  match /onlinestore/elish/admins/{documents} {
  	allow read: if request.auth.uid!=null && request.auth.uid == get(/databases/$(database)/documents/onlinestore/elish/admins/$(request.auth.uid)).data.authid;
  	allow write: if false;
  }
  match /onlinestore/elish/carts/{documents} {
  	allow read: if request.auth.uid!=null && request.auth.uid == get(/databases/$(database)/documents/onlinestore/elish/carts/$(documents)).data.authid;
  	allow write: if request.auth.uid!=null;
  }
  match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2021, 1, 26);
  }
```

Did I understand wrong? I should have an estore collection?

**Comment by AmitXShukla** [comment]
> Did I understand wrong? I should have an estore collection?
> 
> 

I'll download and look into this issue tomorrow.

**Comment by PhMari3** [comment]
The problem is in "admin.login.component.ts", at function "loginAdmin()", "res" is undefined.
If you go to "firebase.service.ts" at function "getAdminPortal (coll ?: string)" and show in console "this.authState.uid" is shown proprietly, but it doesn't get to "loginAdmin ()". "getAdminPortal (coll ?: string)" returns an observable and it makes me very confused

**Comment by AmitXShukla** [comment]
Thanks PhMari3 for helping me debug.

Fact is, as you are able to print "this.authState.uid" in console.log(this.authState.uid) properly, and it displays your uid in console log browser window, tells me, there is nothing wrong in function.
now, what below code is doing, it's going to server (FireBase database), and looking into a collection "estore" (search for_eStoreColl variable defined in Firebase.service.ts which is equal to < estore >).
Further, inside this collection, it's trying to find a document (which has id = your uuid), and in your case, is not able to find it, hence comes back with an error.

Try creating a collection = estore and inside this collection, create a document like this (where id == your uuid) and add fields like show in this link below
look at this image for reference
https://user-images.githubusercontent.com/20031132/71873449-0d25c300-30d4-11ea-82b4-ff38c9fad88c.png

    getAdminPortal(coll?: string){
        if (!coll || coll == "store") { coll = this._eStoreColl; }
        let x;
        return this.getDoc(coll,this.authState.uid);
    }

**Comment by AmitXShukla** [comment]
service cloud.firestore {
match /databases/{database}/documents {
// rules for estore collections
match /estore/{document} {
allow read: if request.auth.uid == get(/databases/$(database)/documents/estore/$(request.auth.uid)).data.authid;
allow write: if false;
}
match /estore/{document}/product/{prods} {
allow read: if true;
allow write: if request.auth.uid == get(/databases/$(database)/documents/estore/$(request.auth.uid)).data.authid;
}
match /estore/{document}/cart/{shoppingcart} {
allow read: if isSignedIn() && isDocOwner();
allow write: if isSignedIn();
}
match /estore/{document}/interests/{shoppingcart} {
allow read: if false;
allow write: if isSignedIn();
} }
}

**Comment by PhMari3** [comment]
I have replaced the rules of my firebase with the ones above and created a collection exactly like shown in the picture (obviesly I have my own authid) and it's still shows: "user not authorized". That field named: "center" makes me very confused. Why do we need it? And the problem wasn't in loginAdmin() function where the received response is undefined? Or the rules and database are responsible for the undefined response? 

This is my firebase
![image](https://user-images.githubusercontent.com/75609966/103812780-155e6880-5070-11eb-80ad-cd0495586e76.png)

This is what is logged in the console. 
![image](https://user-images.githubusercontent.com/75609966/103812388-818c9c80-506f-11eb-9b4c-d240350af3c4.png)

**Comment by AmitXShukla** [comment]
please delete all your firebase rules and change this as below lines.
If this fixes your issue, slowly debug one rule at a time.
These are default settings (not recommended), and will help you debug one rule per document at a time.


rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if true;
    }
  }

**Comment by PhMari3** [comment]
Still not working :/

If I use 
"match /{document=**} {
allow read, write: if true;" 
I get user not authorized and nothing is logged in console

If I use
"match /estore/ {document=**} {
allow read, write: if true;" 
I get user not authorized and this is logged in my console:

![image](https://user-images.githubusercontent.com/75609966/103880242-ea185f80-50e9-11eb-921d-6f25c556979b.png)

**Comment by AmitXShukla** [comment]
alright, it's taking longer than expected to resolve this.
Please send these to me
1. zip all files in your project (except node_modules)
2. run ng version on your terminal window and tell me what Angular version you are using
3. copy paste your firebase rules (before you replaced everything ==true)

You can attach zip file (should be few MBs) to this thread reply.

- Amit

**Comment by PhMari3** [comment]
Angular CLI: 11.0.5
Node: 14.15.1
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

---------------------------------------------------------
Rules for estore collection:
service cloud.firestore {
match /databases/{database}/documents {
match /estore/{document} {
allow read: if request.auth.uid == get(/databases/$(database)/documents/estore/$(request.auth.uid)).data.authid;
allow write: if false;
}
match /estore/{document}/product/{prods} {
allow read: if true;
allow write: if request.auth.uid == get(/databases/$(database)/documents/estore/$(request.auth.uid)).data.authid;
}
match /estore/{document}/cart/{shoppingcart} {
allow read: if isSignedIn() && isDocOwner();
allow write: if isSignedIn();
}
match /estore/{document}/interests/{shoppingcart} {
allow read: if false;
allow write: if isSignedIn();
} }
}

---------------------------------------------------------
Rules for onlinestore collection:
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
  match /onlinestore/{document} {
  	allow read: if false;
  	allow write: if false;
  }
  match /onlinestore/elish/admins/{documents} {
  	allow read: if request.auth.uid!=null && request.auth.uid == get(/databases/$(database)/documents/onlinestore/elish/admins/$(request.auth.uid)).data.authid;
  	allow write: if false;
  }
  match /onlinestore/elish/carts/{documents} {
  	allow read: if request.auth.uid!=null && request.auth.uid == get(/databases/$(database)/documents/onlinestore/elish/carts/$(documents)).data.authid;
  	allow write: if request.auth.uid!=null;
  }
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2021, 1, 26);
    }
  }
}

[Project.zip](https://github.com/AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase/files/5783068/Project.zip)

Thank you very much

**Comment by AmitXShukla** [comment]
Thanks, I'll look into this later today and debug.
Have a nice day.

- Amit

**Comment by jacqdewet** [comment]
Hello, thank you for the great content and amazing videos! 
I started at your first video to learn Angular and has been a great way to get my foot in the door!
I am however stuck on the backend.service.ts file with the isUserAdmin() method.  I get the error: "Property 'auth' does not exist on type 'AngularFireAuth'.ts(2339)" - please see screenshot. I might have missed something - could you perhaps send me in the right direction?

![Capture](https://user-images.githubusercontent.com/21248563/104015798-d5a59700-51bd-11eb-9195-f6c734812409.PNG)

**Comment by AmitXShukla** [comment]
> Hello, thank you for the great content and amazing videos! 
> 
> I started at your first video to learn Angular and has been a great way to get my foot in the door!
> 
> I am however stuck on the backend.service.ts file with the isUserAdmin() method.  I get the error: "Property 'auth' does not exist on type 'AngularFireAuth'.ts(2339)" - please see screenshot. I might have missed something - could you perhaps send me in the right direction?
> 
> 
> 
> ![Capture](https://user-images.githubusercontent.com/21248563/104015798-d5a59700-51bd-11eb-9195-f6c734812409.PNG)
> 
> 

thanks for your kind words, I'm in process of downloading and retesting this code, I'll look into your defect as well. Please expect an answer by Monday.

Amit

**Comment by AmitXShukla** [comment]
> 
> 
> Hello, thank you for the great content and amazing videos!
> I started at your first video to learn Angular and has been a great way to get my foot in the door!
> I am however stuck on the backend.service.ts file with the isUserAdmin() method. I get the error: "Property 'auth' does not exist on type 'AngularFireAuth'.ts(2339)" - please see screenshot. I might have missed something - could you perhaps send me in the right direction?
> 
> ![Capture](https://user-images.githubusercontent.com/21248563/104015798-d5a59700-51bd-11eb-9195-f6c734812409.PNG)

If you are using this code (as you shared in your screenshot above), (I assume you are following youtube video as is).
This is really old code and is not supported by latest Angular 11 version anymore.

Please re-download entire source code (from this repository).
https://github.com/AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase

However, If you must want to sync in YouTube with Latest code, you can always look at history and previous versions of code at GitHub.

- Amit

**Comment by AmitXShukla** [comment]
> 
> 
> Still not working :/
> 
> If I use
> "match /{document=**} {
> allow read, write: if true;"
> I get user not authorized and nothing is logged in console
> 
> If I use
> "match /estore/ {document=**} {
> allow read, write: if true;"
> I get user not authorized and this is logged in my console:
> 
> ![image](https://user-images.githubusercontent.com/75609966/103880242-ea185f80-50e9-11eb-921d-6f25c556979b.png)

Can you please confirm one more thing.
when you pasted following firebase rules, your deleted everything else in your firebase rule window.

rules_version = '2';
service cloud.firestore {
match /databases/{database}/documents {
match /{document=**} {
allow read, write: if true;
}
}

**Comment by AmitXShukla** [comment]
> 
> 
> Still not working :/
> 
> If I use
> "match /{document=**} {
> allow read, write: if true;"
> I get user not authorized and nothing is logged in console
> 
> If I use
> "match /estore/ {document=**} {
> allow read, write: if true;"
> I get user not authorized and this is logged in my console:
> 
> ![image](https://user-images.githubusercontent.com/75609966/103880242-ea185f80-50e9-11eb-921d-6f25c556979b.png)

Can you please confirm one more thing.
Please make sure, when you use this code in FireBase rules (for debugging purpose), you delete every thing in rules tab and copy paste only this.
- Amit

rules_version = '2';
service cloud.firestore {
match /databases/{database}/documents {
match /{document=**} {
allow read, write: if true;
}
}

**Comment by PhMari3** [comment]
Yes, @AmitXShukla. I have used only this rule and still: user not authorized
rules_version = '2';
service cloud.firestore {
match /databases/{database}/documents {
match /{document=**} {
allow read, write: if true;
}
}

**Comment by AmitXShukla** [comment]
> Yes, @AmitXShukla. I have used only this rule and still: user not authorized
> 
> rules_version = '2';
> 
> service cloud.firestore {
> 
> match /databases/{database}/documents {
> 
> match /{document=**} {
> 
> allow read, write: if true;
> 
> }
> 
> }

when you replace these rules, I assume you clicked publish and had no error.
the reason I am so puzzled,
above firebase rules allows every read and write
and if that's the case, you should never see error (missing or insufficient permissions) in your console window.
please copy paste your rules as is one more time please.

**Comment by AmitXShukla** [comment]
> Yes, @AmitXShukla. I have used only this rule and still: user not authorized
> 
> rules_version = '2';
> 
> service cloud.firestore {
> 
> match /databases/{database}/documents {
> 
> match /{document=**} {
> 
> allow read, write: if true;
> 
> }
> 
> }

aren't you missing a } in this code?

**Comment by AmitXShukla** [comment]
> > Yes, @AmitXShukla. I have used only this rule and still: user not authorized
> > 
> > rules_version = '2';
> > 
> > service cloud.firestore {
> > 
> > match /databases/{database}/documents {
> > 
> > match /{document=**} {
> > 
> > allow read, write: if true;
> > 
> > }
> > 
> > }
> 
> when you replace these rules, I assume you clicked publish and had no error.
> the reason I am so puzzled,
> above firebase rules allows every read and write
> and if that's the case, you should never see error (missing or insufficient permissions) in your console window.
> please copy paste your rules as is one more time please.

rules_version = '2';
service cloud.firestore {
match /databases/{database}/documents {
match /{document=**} {
allow read, write: if true;
}
}
}

**Comment by PhMari3** [comment]
I am absolutely sure that my rules are correct, but i've tried both ways and it still shows user not authorized. If you give me your email I can make you editor in my firebase for debugging porposes. I only have a school project so it should be alright

**Comment by AmitXShukla** [comment]
> I am absolutely sure that my rules are correct, but i've tried both ways and it still shows user not authorized. If you give me your email I can make you editor in my firebase for debugging porposes. I only have a school project so it should be alright

you are seeing "user not authorized" error front UI, what do you see in browser console?
amit@elishconsulting.com

Thanks for sharing your project details, and making me editor on your firebase env, perhaps that will help me debug.
- Amit

**Comment by AmitXShukla** [comment]
> 
> 
> I am absolutely sure that my rules are correct, but i've tried both ways and it still shows user not authorized. If you give me your email I can make you editor in my firebase for debugging porposes. I only have a school project so it should be alright

I fixed it, here is the problem
firebase.service.ts
Line #25
change
private _eStoreColl: string = "store";
to
private _eStoreColl: string = "estore";

**Comment by PhMari3** [comment]
![image](https://user-images.githubusercontent.com/75609966/104285689-a6906d80-54bc-11eb-9f6c-90cdf389e67c.png)

No way we've spend hours just to put an "e" before "store" 🤦‍♂️

Thank you very much
