### ISSUE TITLE
Error and commented code

### ISSUE THREAD

**Issue by Shaykoo** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#5]
![Screenshot from 2020-01-02 14-34-58](https://user-images.githubusercontent.com/34743587/71710897-64057100-2e24-11ea-846b-dacc0e1529f3.png)

some of the useful code is commented out from the files and this is the error I am recieving after running latest git repo code. Thanks.

**Comment by Shaykoo** [comment]
And I am not able to understand why are we getting error from one of the node_module file

**Comment by AmitXShukla** [comment]
This has nothing to do with app code. This is Rxjs error in your package.json
This is the reason why I update the code to latest version.
