### ISSUE TITLE
Header and footer don't show

### ISSUE THREAD

**Issue by alerod620** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#7]
Hi, I followed the steps of the videos, but when I execute 'ng serve' the header and footer don't show. 
![(1)](https://user-images.githubusercontent.com/61027811/79189059-06e36900-7dde-11ea-8859-0d56abadad36.png)
![(2)](https://user-images.githubusercontent.com/61027811/79189060-077bff80-7dde-11ea-80f0-d3c431629a32.png)
![(3)](https://user-images.githubusercontent.com/61027811/79189061-08149600-7dde-11ea-9834-38231b5249fb.png)
![(4)](https://user-images.githubusercontent.com/61027811/79189062-08149600-7dde-11ea-8f48-59b3763f859d.png)

**Comment by AmitXShukla** [comment]
Show me your header.component.ts please

**Comment by alerod620** [comment]
Here it is.
![Captura de pantalla de 2020-04-13 23-40-39](https://user-images.githubusercontent.com/61027811/79190038-7ce8cf80-7de0-11ea-9c44-dc3e0a47d3df.png)

**Comment by AmitXShukla** [comment]
Got it.
See error is very clear. 

Your typescript file says, you selector is 
app-header
and you are including 
header
In your app.component.html

Instead of header, type app-header

And same is true for footer.

**Comment by alerod620** [comment]
It works! Thank you! You saved me.
