### ISSUE TITLE
Please give me more instructions

### ISSUE THREAD

**Issue by hoangha090399** [AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase#9]
Hello sir,
I want to ask about the getFilterProducts section.
I did the getFilterProducts part by myself 
But it didn't work.
Hope you can help me.
I am a student and my level is still weak. If it wrong,so you can ignore for me.
I was tried 
Thanks
(version in youtube)
this is setproduct.ts page
![1](https://user-images.githubusercontent.com/49011681/85415365-7375a380-b597-11ea-8775-efdf64899cbf.png)
this is service.ts page
![2](https://user-images.githubusercontent.com/49011681/85415375-74a6d080-b597-11ea-9675-ce9ef9cb6390.png)

I tried the same way in the github file but  error at "...data"
![3](https://user-images.githubusercontent.com/49011681/85417887-5b535380-b59a-11ea-8971-4be7b8fda085.png)

**Comment by AmitXShukla** [comment]
I will sure help you, in your last screen shot, a pop-up describe hide snapshotchange().map....
So, I am not able to see full method implementation
can you please show me that code as well.
![image](https://user-images.githubusercontent.com/20031132/85430804-78097000-b535-11ea-8090-a07440ae87ea.png)

**Comment by hoangha090399** [comment]
Thanks for the reply.
![4](https://user-images.githubusercontent.com/49011681/85443499-88fcc480-b5bb-11ea-9514-a62a5e7d2118.png)
and this is product.ts ( it is setproduct.ts in your video in youtube )
![5](https://user-images.githubusercontent.com/49011681/85443603-ab8edd80-b5bb-11ea-8f7b-a214798336d1.png)

**Comment by hoangha090399** [comment]
I tried writing in many ways but it still didn't work. I think I should learn how it works according to your code on github

**Comment by AmitXShukla** [comment]
I look at original code and see this method doesn't look like yours at all.
I've commented everything after valuechanges();

Line #163
https://github.com/AmitXShukla/Online-Shop-eCommerce-App-Angular-6-Firebase/blob/master/src/app/services/firebase.service.ts

    getFilterProducts(coll: string, filters) {
        return this.afs.collection(this.getCollectionURL(coll), ref =>
        ref.where('delete_flag', '==', 'N')
            .where('tags' , 'array-contains', filters)
            .orderBy('tags', 'desc')
    ).valueChanges();
        // .snapshotChanges()
        // .map(actions => {
        //     return actions.map(a => {
        //         const data = a.payload.doc.data();
        //         const id = a.payload.doc.id;
        //         return { id, ...data };
        //     });
        // });

**Comment by hoangha090399** [comment]
I have understood the problem.

Thank you very much for answering and supporting me.
